import { IExpenseEvent } from './interfaces';

export const sampleEvents: IExpenseEvent[] = [
  {
    id: 'wedding_4f9a7c2b',
    title: 'Wedding Ceremony',
    startDate: '2025-02-10',
    endDate: '2025-02-12',
    isMultiDay: true,
    type: 'group',
    balanceAmount: '7000', // incoming - outgoing
    incomingAmount: '20000',
    outgoingAmount: '13000',
    open: true,
    transactions: [
      {
        id: 'ax008bu',
        amount: '5000',
        type: 'incoming',
        description: 'Contribution from Uncle',
        date: '2025-02-10',
        eventId: 'wedding_4f9a7c2b',
        balanceAmountNow: '5000',
        prevTransactionId: '',
      },
      {
        id: 'by92k3m',
        amount: '7000',
        type: 'incoming',
        description: 'Contribution from Friends',
        date: '2025-02-10',
        eventId: 'wedding_4f9a7c2b',
        balanceAmountNow: '12000',
        prevTransactionId: 'ax008bu',
      },
      {
        id: 'lo8r2wx',
        amount: '8000',
        type: 'incoming',
        description: 'Brides Family Support',
        date: '2025-02-11',
        eventId: 'wedding_4f9a7c2b',
        balanceAmountNow: '20000',
        prevTransactionId: 'by92k3m',
      },
      {
        id: 'qp7t1gh',
        amount: '10000',
        type: 'outgoing',
        description: 'Venue Booking',
        date: '2025-02-11',
        eventId: 'wedding_4f9a7c2b',
        balanceAmountNow: '10000',
        prevTransactionId: 'lo8r2wx',
      },
      {
        id: 'mn6k8vz',
        amount: '3000',
        type: 'outgoing',
        description: 'Catering Services',
        date: '2025-02-12',
        eventId: 'wedding_4f9a7c2b',
        balanceAmountNow: '7000',
        prevTransactionId: 'qp7t1gh',
      },
      {
        id: 'cd2h9tr',
        amount: '0',
        type: 'item',
        itemName: 'Stage Decoration',
        worth: '5000',
        description: '',
        date: '2025-02-11',
        eventId: 'wedding_4f9a7c2b',
        balanceAmountNow: '7000',
        prevTransactionId: 'mn6k8vz',
      },
    ],
  },
  {
    id: 'trip_9a0b6x3q',
    title: 'Goa Trip',
    startDate: '2025-03-05',
    endDate: '2025-03-08',
    isMultiDay: true,
    type: 'personal',
    balanceAmount: '2500',
    incomingAmount: '10000',
    outgoingAmount: '7500',
    open: false,
    transactions: [
      {
        id: 'rt67ujk',
        amount: '4000',
        type: 'incoming',
        description: 'Salary Savings',
        date: '2025-03-04',
        eventId: 'trip_9a0b6x3q',
        balanceAmountNow: '4000',
        prevTransactionId: '',
      },
      {
        id: 'we89opq',
        amount: '6000',
        type: 'incoming',
        description: 'Friends Contribution',
        date: '2025-03-05',
        eventId: 'trip_9a0b6x3q',
        balanceAmountNow: '10000',
        prevTransactionId: 'rt67ujk',
      },
      {
        id: 'vb45tkl',
        amount: '2500',
        type: 'outgoing',
        description: 'Hotel Booking',
        date: '2025-03-05',
        eventId: 'trip_9a0b6x3q',
        balanceAmountNow: '7500',
        prevTransactionId: 'we89opq',
      },
      {
        id: 'zx91mno',
        amount: '3000',
        type: 'outgoing',
        description: 'Travel Tickets',
        date: '2025-03-06',
        eventId: 'trip_9a0b6x3q',
        balanceAmountNow: '4500',
        prevTransactionId: 'vb45tkl',
      },
      {
        id: 'gh34plm',
        amount: '2000',
        type: 'outgoing',
        description: 'Food & Drinks',
        date: '2025-03-07',
        eventId: 'trip_9a0b6x3q',
        balanceAmountNow: '2500',
        prevTransactionId: 'zx91mno',
      },
      {
        id: 'ab12def',
        amount: '0',
        type: 'item',
        itemName: 'Beach Ball',
        worth: '500',
        description: '',
        date: '2025-03-07',
        eventId: 'trip_9a0b6x3q',
        balanceAmountNow: '2500',
        prevTransactionId: 'gh34plm',
      },
    ],
  },
];
